# the problem LSTM solves

print("WHY LSTM?")
print()
print("RNN problem: vanishing gradients")
print()
print("example: 'The cat, which ate the fish, was happy'")
print("         ^^^                            ^^^")
print("         subject                        verb")
print()
print("RNN struggles to connect 'cat' and 'was'")
print("gradient vanishes over many steps")
print()
print("LSTM solution:")
print("  - special 'memory cell' state")
print("  - gates control information flow")
print("  - gradient can flow unchanged!")
print()
print("LSTM = Long Short-Term Memory")
