# cell state - the LSTM memory highway

print("CELL STATE (c)")
print()
print("think of it as a conveyor belt")
print()
print("  c_0 ---> c_1 ---> c_2 ---> c_3 --->")
print("           +/-      +/-      +/-")
print()
print("information flows with minimal changes")
print("gates decide what to add/remove")
print()
print("vs RNN hidden state:")
print("  h_0 --> tanh --> h_1 --> tanh --> h_2")
print("          ^^^^           ^^^^")
print("      squishes      squishes again")
print()
print("cell state avoids repeated squishing!")
print("gradients can flow through unchanged")
