# all LSTM equations together

print("LSTM EQUATIONS")
print("=" * 50)
print()
print("input: x_t, h_{t-1}, c_{t-1}")
print()
print("1. FORGET GATE")
print("   f_t = sigmoid(W_f * [h_{t-1}, x_t] + b_f)")
print()
print("2. INPUT GATE")
print("   i_t = sigmoid(W_i * [h_{t-1}, x_t] + b_i)")
print("   c_tilde = tanh(W_c * [h_{t-1}, x_t] + b_c)")
print()
print("3. CELL STATE UPDATE")
print("   c_t = f_t * c_{t-1} + i_t * c_tilde")
print()
print("4. OUTPUT GATE")
print("   o_t = sigmoid(W_o * [h_{t-1}, x_t] + b_o)")
print("   h_t = o_t * tanh(c_t)")
print()
print("output: h_t, c_t")
print()
print("4 sets of weights: W_f, W_i, W_c, W_o")
print("4x more parameters than simple RNN!")
