# LSTM vs GRU comparison

print("LSTM vs GRU")
print("=" * 40)
print()
print("LSTM:")
print("  - 3 gates (forget, input, output)")
print("  - separate cell state and hidden state")
print("  - more parameters")
print("  - more expressive")
print("  - better for complex sequences")
print()
print("GRU:")
print("  - 2 gates (update, reset)")
print("  - only hidden state")
print("  - fewer parameters (~75% of LSTM)")
print("  - faster to train")
print("  - good for smaller datasets")
print()
print("WHEN TO USE WHAT:")
print("  - default: try both, compare")
print("  - large data: LSTM often better")
print("  - small data/speed: GRU")
print("  - very long sequences: LSTM")
print()
print("both are much better than vanilla RNN!")
