# LSTM applications

print("LSTM APPLICATIONS")
print("=" * 40)
print()
print("LANGUAGE MODELING")
print("  - text generation")
print("  - autocomplete")
print("  - spell checking")
print()
print("MACHINE TRANSLATION")
print("  - encoder-decoder architecture")
print("  - sequence to sequence")
print()
print("SPEECH RECOGNITION")
print("  - audio to text")
print("  - voice assistants")
print()
print("SENTIMENT ANALYSIS")
print("  - review classification")
print("  - social media analysis")
print()
print("TIME SERIES")
print("  - stock prediction")
print("  - weather forecasting")
print("  - anomaly detection")
print()
print("VIDEO ANALYSIS")
print("  - action recognition")
print("  - video captioning")
print()
print("LSTM dominated NLP until transformers (2017+)")
