# typical CNN architecture

print("CNN ARCHITECTURE")
print()
print("INPUT IMAGE")
print("    |")
print("    v")
print("CONV LAYER (filters detect features)")
print("    |")
print("    v")
print("RELU (nonlinearity)")
print("    |")
print("    v")
print("POOLING (downsample)")
print("    |")
print("    v")
print("[repeat conv-relu-pool blocks]")
print("    |")
print("    v")
print("FLATTEN (2D -> 1D)")
print("    |")
print("    v")
print("FULLY CONNECTED (classification)")
print("    |")
print("    v")
print("SOFTMAX (probabilities)")
print()
print("early layers: edges, textures")
print("later layers: shapes, objects")
