# CNN summary

print("=" * 50)
print("CONVOLUTIONAL NEURAL NETWORKS SUMMARY")
print("=" * 50)
print()
print("CONVOLUTION")
print("  - slide kernel/filter across image")
print("  - element-wise multiply and sum")
print("  - detects local patterns (edges, textures)")
print("  - parameters: kernel_size, stride, padding")
print()
print("POOLING")
print("  - downsample feature maps")
print("  - max pooling: take maximum in each window")
print("  - avg pooling: take average")
print("  - reduces size and computation")
print()
print("CNN LAYERS")
print("  - Conv2D: learnable filters")
print("  - ReLU: nonlinearity")
print("  - Pool: downsample")
print("  - Flatten: 2D -> 1D")
print("  - Dense: classification")
print()
print("KEY IDEAS")
print("  - local connectivity")
print("  - parameter sharing")
print("  - translation invariance")
print("  - hierarchical features")
print()
print("CNNs = standard for image tasks!")
