# different RNN architectures

print("RNN ARCHITECTURES")
print()
print("ONE-TO-MANY")
print("  input: single item")
print("  output: sequence")
print("  example: image captioning")
print()
print("MANY-TO-ONE")
print("  input: sequence")
print("  output: single item")
print("  example: sentiment analysis")
print()
print("MANY-TO-MANY (same length)")
print("  input: sequence")
print("  output: sequence (same length)")
print("  example: POS tagging")
print()
print("MANY-TO-MANY (different length)")
print("  input: sequence")
print("  output: sequence (different length)")
print("  example: translation (encoder-decoder)")
print()
print("all use same RNN cell, different configurations!")
