# Backpropagation Through Time (BPTT)

print("BACKPROPAGATION THROUGH TIME (BPTT)")
print()
print("problem: how to compute gradients for RNNs?")
print()
print("solution: unroll the network, then backprop!")
print()
print("                   loss")
print("                    |")
print("   h0 -> h1 -> h2 -> h3 -> output")
print("         |     |     |")
print("        x1    x2    x3")
print()
print("gradients flow backward through time:")
print("  - from loss to h3")
print("  - from h3 to h2")
print("  - from h2 to h1")
print("  - etc.")
print()
print("same weights at each step")
print("-> sum gradients from all timesteps!")
