# RNN applications

print("RNN APPLICATIONS")
print("=" * 40)
print()
print("NATURAL LANGUAGE PROCESSING")
print("  - language modeling (predict next word)")
print("  - sentiment analysis")
print("  - machine translation")
print("  - text generation")
print("  - named entity recognition")
print()
print("SPEECH")
print("  - speech recognition")
print("  - text-to-speech")
print()
print("TIME SERIES")
print("  - stock prediction")
print("  - weather forecasting")
print("  - anomaly detection")
print()
print("SEQUENCE-TO-SEQUENCE")
print("  - translation")
print("  - summarization")
print("  - chatbots")
print()
print("OTHER")
print("  - music generation")
print("  - video analysis")
print("  - handwriting recognition")
