# why does overfitting happen?

print("CAUSES OF OVERFITTING:")
print()
print("1. Model too complex")
print("   - too many parameters")
print("   - can memorize noise")
print()
print("2. Not enough data")
print("   - easy to memorize small dataset")
print("   - not enough examples to generalize")
print()
print("3. Training too long")
print("   - starts learning, then memorizing")
print("   - need to stop at the right time")
print()
print("4. Noisy data")
print("   - model learns the noise too")
print()
print("SOLUTIONS: regularization techniques!")
