# comparing regularization techniques

print("REGULARIZATION COMPARISON")
print("=" * 40)
print()
print("EARLY STOPPING")
print("  + simple to implement")
print("  + no extra computation")
print("  - need validation set")
print("  - must save best weights")
print()
print("DROPOUT")
print("  + very effective")
print("  + acts like ensemble")
print("  - slower training")
print("  - need to tune keep_prob")
print()
print("L2 REGULARIZATION")
print("  + smooth, differentiable")
print("  + keeps weights small")
print("  - doesnt make weights exactly 0")
print()
print("L1 REGULARIZATION")
print("  + creates sparse weights")
print("  + feature selection")
print("  - non-smooth at 0")
print()
print("often combine multiple techniques!")
