# regularization summary

print("=" * 50)
print("REGULARIZATION SUMMARY")
print("=" * 50)
print()
print("PROBLEM: Overfitting")
print("  - model memorizes training data")
print("  - fails to generalize to new data")
print()
print("SOLUTIONS:")
print()
print("1. Early Stopping")
print("   - monitor validation error")
print("   - stop when it starts increasing")
print()
print("2. Dropout")
print("   - randomly drop neurons during training")
print("   - typical keep_prob: 0.5-0.8")
print("   - scale outputs appropriately")
print()
print("3. L2 Regularization (Weight Decay)")
print("   - penalize sum of squared weights")
print("   - loss += lambda * sum(w^2)")
print()
print("4. L1 Regularization")
print("   - penalize sum of absolute weights")
print("   - creates sparse networks")
print()
print("5. Data Augmentation")
print("   - create more training data")
print("   - rotations, flips, noise, etc.")
print()
print("RULE: start simple, add regularization if overfitting")
