# Word2Vec - learning embeddings from context

print("WORD2VEC")
print()
print("key insight: words with similar context = similar meaning")
print()
print('"you shall know a word by the company it keeps"')
print()
print("example contexts:")
print('  "the ___ sat on the mat"')
print('  "the ___ chased the mouse"')
print('  "I pet my ___"')
print()
print("what words fit? cat, dog, kitten...")
print("these words should have similar embeddings!")
print()
print("two architectures:")
print("  1. CBOW: predict word from context")
print("  2. Skip-gram: predict context from word")
