# CBOW - Continuous Bag of Words

print("CBOW: Continuous Bag of Words")
print()
print("task: predict center word from surrounding words")
print()
print('sentence: "the cat sat on the mat"')
print('window size = 2')
print()
print("training examples:")
print('  context: [the, sat]     -> target: cat')
print('  context: [cat, on]      -> target: sat')
print('  context: [sat, the]     -> target: on')
print()
print("architecture:")
print("  context words -> average embeddings -> predict center")
print()
print("   [the]  \\")
print("           } -> average -> hidden -> softmax -> [cat]")
print("   [sat]  /")
print()
print("learns embeddings that predict well")
