# Skip-gram - predict context from word

print("SKIP-GRAM")
print()
print("opposite of CBOW:")
print("  predict context words from center word")
print()
print('sentence: "the cat sat on the mat"')
print('window size = 2')
print()
print("training examples from center word 'sat':")
print('  input: sat -> target: cat')
print('  input: sat -> target: on')
print()
print("architecture:")
print("  center word -> embedding -> predict each context word")
print()
print("   [sat] -> embed -> softmax -> [cat]")
print("                  -> softmax -> [on]")
print()
print("skip-gram often works better for rare words")
print("CBOW is faster")
